# Generated by Django 5.2.3 on 2025-06-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Usuario',
        ),
    ]
